# Generated by Django 4.0.6 on 2022-07-09 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('receiver', 'sender'), ('sender', 'receiver')},
        ),
    ]
